---
name: CD
on:
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch: null
jobs:
  scrape-prices:
    name: Scrape Graphic Novel Prices
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Update CSV
        run: |
          git clone https://github.com/grayespinoza/retail-price-scraper.git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          set +e
          mv isbns.csv retail-price-scraper/
          cd retail-price-scraper/
          python -m scripts.scrape_prices
          mv prices_*.csv ../prices/
          cd ../
          git add prices/prices_*.csv
          git commit -m "chore: update prices"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
      - name: Clean Up
        if: always()
        run: rm -rf retail-price-scraper
