---
name: CD
on:
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch: null
jobs:
  scrape-prices:
    name: Scrape Graphic Novel Prices
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Update CSV
        run: |
          git clone https://github.com/grayespinoza/graphic-novel-price-scraper.git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          set +e
          mv isbns.csv graphic-novel-price-scraper/
          cd graphic-novel-price-scraper/
          pip install playwright
          playwright install --with-deps --only-shell
          python -m scripts.scrape_prices
          mv prices_*.csv ../prices/
          cd ../
          git add prices/prices_*.csv
          git commit -m "chore: update prices"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
  publish:
    name: Publish Database
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    needs: scrape-prices
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Update Database
        run: |
          git clone https://github.com/grayespinoza/graphic-novel-price-scraper.git
          head -n 1 prices/prices_260602.csv > prices.csv
          tail -n +2 -q prices/*.csv >> prices.csv
          mv prices.csv graphic-novel-price-scraper/
          cd graphic-novel-price-scraper/
          python -m scripts.create_database
          mv graphic_novels.db ../
          cd ../
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: graphic_novels.db
          name: latest
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
